// webapp/src/components/StatusBadge.tsx
interface StatusBadgeProps {
  status?: "ok" | "error";
  variant?: "default" | "healthy" | "error";
}

export function StatusBadge({ status, variant = "default" }: StatusBadgeProps) {
  if (variant === "healthy") {
    return (
      <span className="px-2 py-0.5 rounded-full text-xs bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300">
        Healthy
      </span>
    );
  }

  if (variant === "error") {
    return (
      <span className="px-2 py-0.5 rounded-full text-xs bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300">
        Error
      </span>
    );
  }

  if (status === "ok") {
    return (
      <span className="px-2 py-0.5 rounded-full text-xs bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300">
        Healthy
      </span>
    );
  }

  if (status === "error") {
    return (
      <span className="px-2 py-0.5 rounded-full text-xs bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300">
        Error
      </span>
    );
  }

  return null;
}

// webapp-vuejs/src/components/StatusBadge.vue
<template>
  <span
    class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium"
    :class="statusClasses"
  >
    <div class="w-1.5 h-1.5 rounded-full mr-1.5" :class="indicatorClasses" />
    {{ statusText }}
  </span>
</template>

<script setup lang="ts">
import { computed } from 'vue'

interface Props {
  status?: 'ok' | 'error'
}

const props = defineProps<Props>()

const statusText = computed(() => {
  return props.status === 'ok' ? 'Healthy' : 'Error'
})

const statusClasses = computed(() => {
  if (props.status === 'ok') {
    return 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300'
  } else {
    return 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300'
  }
})

const indicatorClasses = computed(() => {
  return props.status === 'ok' ? 'bg-green-500' : 'bg-red-500'
})
</script>
