// webapp-vuejs/src/components/FeatureCard.vue
<template>
  <div
    class="group relative rounded-xl border bg-card p-6 shadow-sm transition-all duration-200 hover:shadow-md"
  >
    <!-- Color accent -->
    <div class="absolute top-0 left-0 w-full h-1 rounded-t-xl" :class="colorClasses" />

    <div class="space-y-3">
      <h3 class="text-lg font-semibold group-hover:text-primary transition-colors">
        {{ title }}
      </h3>
      <p class="text-sm text-muted-foreground leading-relaxed">
        {{ desc }}
      </p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

interface Props {
  title: string
  desc: string
  color: 'emerald' | 'violet' | 'sky' | 'amber' | 'rose' | 'slate'
}

const props = defineProps<Props>()

const colorClasses = computed(() => {
  const colors = {
    emerald: 'bg-gradient-to-r from-emerald-500 to-emerald-600',
    violet: 'bg-gradient-to-r from-violet-500 to-violet-600',
    sky: 'bg-gradient-to-r from-sky-500 to-sky-600',
    amber: 'bg-gradient-to-r from-amber-500 to-amber-600',
    rose: 'bg-gradient-to-r from-rose-500 to-rose-600',
    slate: 'bg-gradient-to-r from-slate-500 to-slate-600',
  }
  return colors[props.color]
})
</script>

// webapp/src/components/FeatureCard.tsx
interface FeatureCardProps {
  title: string;
  desc: string;
  color: "emerald" | "violet" | "sky" | "amber" | "rose" | "slate";
}

export function FeatureCard({ title, desc, color }: FeatureCardProps) {
  const colorMap: Record<typeof color, string> = {
    emerald: "from-emerald-500/10",
    violet: "from-violet-500/10",
    sky: "from-sky-500/10",
    amber: "from-amber-500/10",
    rose: "from-rose-500/10",
    slate: "from-slate-500/10",
  } as const;

  return (
    <div className="group relative overflow-hidden rounded-xl border bg-card p-6 shadow-sm transition-all hover:shadow-md">
      <div
        className={`pointer-events-none absolute inset-0 -z-10 bg-gradient-to-br ${colorMap[color]} to-transparent opacity-0 transition-opacity duration-300 group-hover:opacity-100`}
      />
      <h3 className="text-base font-semibold">{title}</h3>
      <p className="mt-2 text-sm text-muted-foreground">{desc}</p>
    </div>
  );
}
