// webapp-vuejs/src/components/GradientBackground.vue
<template>
  <div class="absolute inset-0 overflow-hidden pointer-events-none">
    <!-- Gradient orbs -->
    <div
      class="absolute -top-40 -right-40 w-80 h-80 bg-gradient-to-br from-emerald-400/20 to-transparent rounded-full blur-3xl"
    />
    <div
      class="absolute -bottom-40 -left-40 w-80 h-80 bg-gradient-to-tr from-violet-400/20 to-transparent rounded-full blur-3xl"
    />
    <div
      class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-gradient-to-r from-sky-400/10 to-emerald-400/10 rounded-full blur-3xl"
    />

    <!-- Grid pattern -->
    <div class="absolute inset-0 bg-grid-pattern opacity-5" />
  </div>
</template>

<style scoped>
.bg-grid-pattern {
  background-image:
    linear-gradient(rgba(0, 0, 0, 0.1) 1px, transparent 1px),
    linear-gradient(90deg, rgba(0, 0, 0, 0.1) 1px, transparent 1px);
  background-size: 20px 20px;
}
</style>

// webapp/src/components/GradientBackground.tsx
export function GradientBackground() {
  return (
    <div className="pointer-events-none absolute inset-0 -z-10">
      <div className="absolute left-1/2 top-[-10%] h-[40rem] w-[40rem] -translate-x-1/2 rounded-full bg-[radial-gradient(circle_at_center,theme(colors.violet.500/.25),transparent_60%)] blur-3xl" />
      <div className="absolute right-[-10%] bottom-[-10%] h-[30rem] w-[30rem] rounded-full bg-[radial-gradient(circle_at_center,theme(colors.sky.500/.25),transparent_60%)] blur-3xl" />
    </div>
  );
}
